name: main

run-name: ${{ github.actor }} is running pipeline on main

on:
  push:
    branches:
      - "main"

env:
  TEST_TAG: cypher4859/cowabunga-pizza:test
  LATEST_TAG: cypher4859/cowabunga-pizza:latest


jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Debugging Check path
        run: |
          cd ../
          pwd && ls -l .

      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}

      - name: Run Tests
        run: |
          docker run --rm ${{ env.TEST_TAG }}          
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: user/app:latest