name: main
run-name: ${{ github.actor }} is running pipeline on main
on:
  push:
    branches:
      - "main"
      - "demo-for-video-recording"


env:
  DEV_TAG: "cypher4859/cowabunga-pizza:dev"
  TEST_TAG: "cypher4859/cowabunga-pizza:test"
  LATEST_TAG: "cypher4859/cowabunga-pizza:latest"

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push dev
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.DEV_TAG }}

      - name: Build and push latest
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.LATEST_TAG }}
      